---
version: 3

build_arg_defaults:
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: '-c'

dependencies:
  ansible_core:
    package_pip: ansible-core==2.15.0
  ansible_runner:
    package_pip: ansible-runner
  galaxy: requirements.yml
  python: requirements.txt
  python_interpreter:
      package_system: "python39"  
      python_path: "/usr/bin/python3.9"
  system: bindep.txt

images:
  base_image:
    name: automationhub.bpic.mainline.com/ee-supported-rhel8-aap24:1.0.0-354 
    # Other available base images:
    #   - quay.io/rockylinux/rockylinux:9
    #   - quay.io/centos/centos:stream9
    #   - registry.fedoraproject.org/fedora:38
    #   - registry.redhat.io/ansible-automation-platform-23/ee-minimal-rhel8:latest
    #     (needs an account)

# Custom package manager path for the RHEL based images
options:
  package_manager_path: /usr/bin/microdnf
  container_init:
      cmd: '["sh"]'
additional_build_files: 
    - src: ansible.cfg
      dest: configs

additional_build_steps:
  prepend_base: 
    - RUN echo This is a prepend base command!
    # Enable Non-default stream before packages provided by it can be installed. (optional)
    # - RUN $PKGMGR module enable postgresql:15 -y
    # - RUN $PKGMGR install -y postgresql
  prepend_galaxy:
    - ADD _build/configs/ansible.cfg /etc/ansible/ansible.cfg

  prepend_final: | 
    RUN whoami
    RUN cat /etc/os-release
  append_final: 
    - RUN echo This is a post-install command! 
    - RUN ls -la /etc

